on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Merge main into dev
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout dev
        git merge main
        git push
